version: '2.3'

services:

  app:
    image: docker.pkg.github.com/biodatamininggroup/ifealid/app
    build:
      dockerfile: .docker/app.dockerfile
      context: ./
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
      - dbdata:/db
    environment:
      - "DB_DATABASE=/db/database.sqlite"

  web:
    image: docker.pkg.github.com/biodatamininggroup/ifealid/web
    depends_on:
      - app
    build:
      context: ./
      dockerfile: .docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
    ports:
      - 8000:80

  # scheduler:
  #   image: docker.pkg.github.com/biodatamininggroup/ifealid/app
  #   volumes_from:
  #     - app
  #   command: "/bin/sh -c 'trap exit TERM; while sleep 60 & wait; do php -d memory_limit=1G artisan schedule:run >> /dev/null 2>&1; done'"

volumes:
  dbdata:

